version: '3.8'
services:
  # Update this to the name of the service you want to work with in your docker-compose.yml file
  frontend:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm

    volumes:
      - ..:/radar:cached

    depends_on:
      db:
        condition: service_healthy

    command: sleep infinity

  db:
    image: mysql
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=radar
      - MYSQL_ROOT_PASSWORD=localhost
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 5s
      interval: 5s
      retries: 40
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
